server:
  port: 1322
reader:
  path: "d:/books"
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  web:
    resources:
      static-locations: classpath:/
